In [1]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print(type(numbers))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [3]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[2])
print(numbers[-1])

10
30
50


In [4]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[1:4])
print(numbers[:3])
print(numbers[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [5]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 85],
    [90, 88, 95]
])

print(marks)
print("Shape:", marks.shape)

[[80 75 90]
 [65 70 85]
 [90 88 95]]
Shape: (3, 3)


In [6]:
print(marks[0, 0])
print(marks[1, 2])
print(marks[2, 1])

80
85
88


In [7]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 85],
    [90, 88, 95]
])

print("Overall Average:", np.mean(marks))
print("Highest Mark:", np.max(marks))
print("Lowest Mark:", np.min(marks))

Overall Average: 82.0
Highest Mark: 95
Lowest Mark: 65
